# Site Settings
title: Mathijs Follon
email: contact@mathijsfollon.be
description: >-
  Portfolio
baseurl: ""
url: "https://mathijsfollon.be"
github_username: mathijs-follon

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include _pages directory
include:
  - _pages

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav:
  - title: "About"
    url: "/about/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/projects/"

# Social links
social:
  github: "https://github.com/mathijs-follon"
  linkedin: "https://linkedin.com/in/mathijs-follon-848411271"

# Footer
footer:
  content: "Mathijs Follon. All rights reserved."

# Exclude from processing
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - .ruby-version
  - .rbenv-version
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
